name: widget_generator
description:  A powerful and flexible CLI tool for generating Dart code snippets and templates with ease.
version: 1.0.0+1
repository: https://github.com/ysavr/widget_generator

environment:
  sdk: ^3.6.0

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  widget_generator: widget_generator
